title: Katherine Donnally
email: kbd3ax@virginia.edu
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Katherine Donnally. Web design, 
  political & social justice, lipstick. A work in progress.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://katherinedonnally.design" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kbdonnally
github_username:  kbdonnally

# Build settings
incremental: true
sass:
  sass_dir: assets/css/_sass
  style: expanded # temporary! change back to compressed later
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
